---
- name: Create multiple EC2 instances
  hosts: localhost
  connection: local
  gather_facts: False

  collections:
  - amazon.aws

  vars:
    instance_count: 3

  tasks:
  - name: Create EC2 key pair
    amazon.aws.ec2_key:
      name: my-key
      region: us-east-1
      state: present
      file_name: "~/.ssh/my-key.pem"

  - name: Launch EC2 instances
    amazon.aws.ec2_instance:
      name: "web-server"
      key_name: my-key
      region: us-east-1
      instance_type: t2.micro
      image_id: ami-0c02fb55956c7d316 # Make sure this AMI ID is valid for your region
      wait: yes
      count: "{{ instance_count }}"
      vpc_subnet_id: subnet-xxxxxxxx # Replace with your actual subnet ID
      security_group: my-sg
      network:
        assign_public_ip: true
      tags:
        Environment: Test
      exact_count: "{{ instance_count }}"
      count_tag:
        Name: web-server
    register: ec2

  - name: Add new instances to inventory
    add_host:
      hostname: "{{ item.public_ip_address }}"
      groupname: launched
    loop: "{{ ec2.instances }}"

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_ip_address }}"
      port: 22
      timeout: 300
      state: started
    loop: "{{ ec2.instances }}"
