---
- name: Configure EC2 instances with Nginx
  hosts: launched
  become: true

  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install Nginx
    apt:
      name: nginx
      state: present

  - name: Copy custom index.html
    copy:
      src: files/index.html
      dest: /var/www/html/index.html
      mode: '0644'
